<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ledger</string>
	</array>
	<key>foldingStartMarker</key>
	<string>^\d{4}[/-]\d{2}[/-]\d{2}.*</string>
	<key>foldingStopMarker</key>
	<string>^\s*$</string>
	<key>keyEquivalent</key>
	<string>^~L</string>
	<key>name</key>
	<string>Ledger</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.type</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(\d{4}[/-]\d{2}[/-]\d{2})\s+(.+)$</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.amount</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s+([\w\:\_\-]+)\s+([\-\$\d\.]+)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.class.variant</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s+([\w\:]+)\s+$</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\;.+)$</string>
			<key>name</key>
			<string>comment</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.ledger</string>
	<key>uuid</key>
	<string>66ECAE19-1421-45CE-AA25-5019FECDB1C9</string>
</dict>
</plist>
